config/routes.rb
Zaglushka::Application.routes.draw do

  #root :to => 'welcome#index'
  root :to => 'welcome#travels'

  get '75daysofeurope', to: 'welcome#travels'

  match 's/:id' => 'shorts#show', :as => 's_id'

  resources :users do
    get :delete_city
    get :shared_to
  end

  resources :cities, :only => [:create]

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
  end

  if Rails.env.production?
    get "/404", :to => "exceptions#show"
    get "/422", :to => "exceptions#show"
    get "/500", :to => "exceptions#show"
  end

  if Rails.env.development?
    mount UserMailer::Preview => 'preview_email'
  end
end

app/models/city.rb
class City
  include Mongoid::Document
  field :name, type: String
  field :latitude, type: String
  field :longitude, type: String
  field :g_id, type: String
  require 'proj4'

  has_and_belongs_to_many :users
  belongs_to :country

  before_destroy { users.clear }

  IMAGE_GLOBE_SIZE = 1200.0
  IMAGE_GLOBE_CENTER_X = 557.0
  IMAGE_GLOBE_CENTER_Y = 360.0
  DEGREES_TO_RADIANS = Math::PI / 180
  RADIANS_TO_PIXELS = IMAGE_GLOBE_SIZE / (2.0 * Math::PI)
  GOOGLE_PARAMS = "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs"
  MILLER_PARAMS = "+proj=mill +lat_0=0 +lon_0=0 +x_0=0 +y_0=0 +R_A +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

  def longitude_in_px
    (IMAGE_GLOBE_CENTER_X + (google_to_miller.x * RADIANS_TO_PIXELS)).to_i
  end

  def latitude_in_px
    f = [ [ Math.sin(google_to_miller.y), -0.9999 ].max, 0.9999 ].min
    (IMAGE_GLOBE_CENTER_Y + (0.5 * Math.log((1.0 + f) / (1.0 - f)) * -RADIANS_TO_PIXELS)).to_i
  end

  def google_to_miller
    google_projection = Proj4::Projection.new(GOOGLE_PARAMS)
    miller_projection = Proj4::Projection.new(MILLER_PARAMS)
    google_location = Proj4::Point.new(
          longitude.to_f * DEGREES_TO_RADIANS,
          latitude.to_f * DEGREES_TO_RADIANS)

    miller_location = google_projection.transform(miller_projection, google_location)
  end

  def user_percentage
    (users.count.to_f / User.count * 100).round
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  expose(:city) { City.find_or_create_by(name: params[:city][:name],
                                    latitude: params[:city][:latitude],
                                    longitude: params[:city][:longitude],
                                    g_id: params[:city][:g_id])}
  expose(:cities)
  expose(:user) {User.find(params[:user_id]) if params[:user_id]}
  before_filter :require_login, :only => :create

  def create
    respond_to do |format|
      country = Country.find_or_initialize_by(name: params[:city][:country])
      country.cities << city unless country.city_ids.include?(city.id)
      country.users << user unless country.user_ids.include?(user.id)
      country.save
      city.country = country
      city.save
      unless user.cities.include?(city)
        city.users << user
        user.add_city_to_image_world_map(city)
        format.js
      else
        format.js { render partial: 'error'}
      end
    end
  end

end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_city.html.haml
%li= city.name

app/views/cities/_error.js.erb
city = $('#city_name_auto')
city.switchClass('', 'wrong', 200);
setTimeout((function() {
return city.switchClass('wrong', '', 200);
}), 3000);

app/views/cities/_form.html.haml
= simple_form_for city, remote: true do |f|
  .field
    = label_tag :city_name_auto, 'Город'
    = text_field_tag :city_name_auto
  = f.input :name, as: :hidden
  = f.input :latitude, as: :hidden
  = f.input :longitude, as: :hidden
  = f.input :g_id, as: :hidden
  = hidden_field_tag :user_id, user.id if user

app/views/cities/create.js.erb
gon.cities_count = <%= user.city_count %>
gon.map_image = '<%= user.world_map_name %>'
gon.cities['<%= city.id %>'] = {name: "<%= city.name %>, <%= city.country.name %>", latitude: '<%= city.latitude %>', longitude: '<%= city.longitude %>', user_percentage: "<%= city.user_percentage %>" }

$('#cities_count').parent().find('.label').html("<%= Russian::p(user.city_count.to_i, 'ГОРОД', 'ГОРОДА', 'ГОРОДОВ')%>")
$('#countries_count').parent().find('.label').html("<%= Russian::p(user.countries_count.to_i, 'СТРАНА', 'СТРАНЫ', 'СТРАН') %>")

$('#city_name_auto').blur();
setTimeout(function(){
  $('#city_name_auto').val('');
  $('#city_name_auto').focus();
},10);

show_city_in_maps('<%= city.id %>', '<%= "#{city.name}, #{city.country.name}" %>', '<%= city.latitude %>', '<%= city.longitude %>', true)

$('.counters.hide').show('drop', {direction: 'up'})
$('.finish_my_map.hide').show('drop', {direction: 'up'})

before_cities = $('#cities_count').html()
before_countries = $('#countries_count').html()

if (before_cities != "<%= user.city_count %>") {
  $('#cities_count').html('<%= user.city_count %>').effect('bounce', {times:3}, 600)
}

if (before_countries != "<%= user.countries_count %>") {
  $('#countries_count').html('<%= user.countries_count %>').effect('bounce', {times:3}, 600)
}

if ($('#map_welcome').length > 0) {
  $('#map_welcome').hide('drop', {direction: 'down'}, function() {
    $('#city_name_auto').appendTo('.header').addClass('outside').attr('placeholder', 'Добавить еще город?').focus();
    $('#map_welcome').remove();
  });
}

// Update share info
$('.share_container a.twitter').attr('href', "https://twitter.com/intent/tweet?&text=<%= user.share_text %> <%= request.protocol %><%= request.host_with_port %>/s/<%= user.short_id %>")
$('.share_container a.vk').attr('href', "http://vk.com/share.php?url=<%= request.protocol %><%= request.host_with_port %>/s/<%= user.short_id %>&title=Follow My Travel&description=<%= user.share_text %>&image=<%= request.protocol %><%= request.host_with_port %>/<%= user.world_map_name %>")

app/views/cities/edit.html.haml
%h1 Editing city

= render 'form'

= link_to 'Show', @city
\|
= link_to 'Back', cities_path

app/views/cities/index.html.haml
%h1 Listing cities

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @cities.each do |city|
    %tr
      %td= city.name
      %td= link_to 'Show', city
      %td= link_to 'Edit', edit_city_path(city)
      %td= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New City', new_city_path

app/views/cities/new.html.haml
%h1 New city

= render 'form'

= link_to 'Back', cities_path

app/views/cities/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @city.name

= link_to 'Edit', edit_city_path(@city)
\|
= link_to 'Back', cities_path